benchmark/README.md, benchmark/index.html, benchmark/index.js, examples/mobilenet/MobileNet.js, examples/mobilenet/index.html, examples/mobilenet/utils.js, examples/squeezenet/SqueezeNet.js, examples/squeezenet/index.html, examples/squeezenet/utils.js, examples/util/base.js
=> [benchmark] Support SqueezeNet for benchmark test.

docs/supported_ops.md
=> Add supported ops

examples/mobilenet/camera.html, examples/squeezenet/camera.html
The issue was introduced by https://github.com/intel/webml-polyfill/pull/34
=> [Example] Fix the base.js missing issue in camera examples

README.md, docs/webml.idl, test/wpt/interfaces/webml.idl, test/wpt/resources/LICENSE, test/wpt/resources/WebIDLParser.js, test/wpt/resources/idlharness.js, test/wpt/resources/testharness.css, test/wpt/resources/testharness.js, test/wpt/resources/testharnessreport.js, test/wpt/webml/idlharness.html
=> [test] Add IDL test for Web ML Polyfill API.

benchmark/index.js, examples/mobilenet/utils.js, examples/squeezenet/utils.js, examples/ssd_mobilenet/utils.js
=> [benchmark] Highlight test score.

src/nn/webgl2/layers/fundamental/Activation.js, src/nn/webgl2/utils/modelUtils.js, src/nn/webgl2/webgl/fragmentShader/activation/index.js, src/nn/webgl2/webgl/fragmentShader/activation/softmax.js
=> [WebGL2] revise softmax

benchmark/index.html
=> [benchmark] Update bootstrap.min.css link.

test/unit-test/test-Model.js
=> [test] Add test cases for the fuse code input of some operations.

src/nn/webgl2/layers/convolution/DepthwiseConv2D.js, src/nn/webgl2/webgl/fragmentShader/arithmetic/matMulDepthwise.js, src/nn/webgl2/webgl/fragmentShader/convolution/depthwiseConv2D.js
Add the use of depth multiplier.
=> [WebGL2] Modify depthwise convolution

examples/mobilenet/MobileNet.js, examples/mobilenet/TfLiteModelUtils.js
=> Support ADD operator in MobileNet.js for MobileNetV2

src/nn/webgl2/WebGL2.js
=> [WebGL2] generate error message before release all resources

src/nn/Execution.js, src/nn/webgl2/Model.js, src/nn/webgl2/layers/fundamental/Concatenation.js, src/nn/webgl2/layers/pooling/_Pool2D.js
#95 4D shapes are supported now.
=> Supported the 4D shapes

src/nn/webgl2/Model.js, src/nn/webgl2/layers/fundamental/Add.js, src/nn/webgl2/layers/fundamental/Input.js, src/nn/webgl2/layers/fundamental/Mul.js, src/nn/webgl2/layers/fundamental/index.js, src/nn/webgl2/utils/modelUtils.js, src/nn/webgl2/webgl/fragmentShader/arithmetic/add.js, src/nn/webgl2/webgl/fragmentShader/arithmetic/index.js, src/nn/webgl2/webgl/fragmentShader/arithmetic/mul.js
=> [WebGL2] Support ADD&MUL operator and example "simple"

examples/posenet/src/helperFunc.js
user could load model from local directory through changing urlBase
=> [Example] Update model load

examples/mobilenet/MobileNet.js, examples/mobilenet/schema/README.md, examples/mobilenet/schema/schema_generated.js
=> Support mobilenet_v1_1.0_224/Update schema for mobilenet/Enhance README.md for generating schema

test/cts/test/V1_0/softmax_float_1.js, test/cts/test/V1_0/softmax_float_2.js, test/cts/test/cts-all.js, test/cts/tool/CTSConverter/src/test_generator.py
=> [test] Fix issue "scale of FLOAT32 type was set with dimensions".

benchmark/index.html, benchmark/index.js, examples/mobilenet/MobileNet.js, examples/mobilenet/camera.js, examples/mobilenet/main.js, examples/posenet/camera.js, examples/posenet/main.js, examples/posenet/src/PoseNet.js, examples/squeezenet/SqueezeNet.js, examples/squeezenet/main.js, examples/ssd_mobilenet/SsdMobileNet.js, examples/util/base.js
=> [benchmark][examples] Enable benchmark test and examples to support BNNS backend on Mac OS.

test/utils.js
=> [test] Use 5ULP of FP16 range for MPS computes on FP16. Fixes #65.

test/unit-test/test-Model.js
=> [test] Correct operand option of some test cases for 'CONV_2D', 'DEPHWISE_CONV_2D', and 'SOFTMAX'.

benchmark/README.md, benchmark/index.html, benchmark/index.js, benchmark/posenetConfig.json, examples/mobilenet/index.html, examples/posenet/src/PoseNet.js, examples/posenet/utils.js, examples/squeezenet/index.html, examples/ssd_mobilenet/index.html
=> [benchmark] Fixes #125  Add PoseNet into Benchmark Test.

src/nn/webgl2/Model.js, src/nn/webgl2/layers/fundamental/Input.js
This memory leak caused the benchmark to crash and be inaccurate.
=> [WebGL2] Revise InputLayer to fix memory leak

examples/image_classification_tflite/utils.js
=> [Image classification Sample] Update utils.deleteAll():Only used for webml-polyfill

examples/image_classification_tflite/model/README.md
=> [Image classification sample]Correct the model version in README.md

examples/ssd_mobilenet/camera.html, examples/ssd_mobilenet/camera.js, examples/ssd_mobilenet/index.html, examples/ssd_mobilenet/main.js
Example "ssd_mobilenet" used to call main.js and camera.js in example "mobilenet". Now add them to "ssd_mobilenet" for the change of "mobilenet" to "image_classification_tflite".
=> [Example] Add main.js and camera.js for example ssd_mobilenet

test/unit-test/test-Model.js
@huningxin @ibelem PTAL, thanks.
=> [test] Add more Unit test cases for supported ops.

test/unit-test/test-Model.js
=> [test] Fix the ReferenceError "batch_size_output is not defined".

src/nn/webgl2/layers/fundamental/FullyConnected.js, src/nn/webgl2/layers/fundamental/index.js, src/nn/webgl2/utils/modelUtils.js
Test by latest 12 CTS test case:
pass:5 fail:7
Temporarily support 1D/2D only. 
Fix #228
=> [WebGL2] support FULLY_CONNECTED op

test/tools/RegressionChecker/baseline/baseline.config.json, test/tools/RegressionChecker/baseline/unitTestsBaseline.csv
=> [tool] Update baseline data of RegressionChecker tool with WASM and WebGL2 backends supporting FC op.

test/tools/CI/baseline/baseline.config.json, test/tools/CI/baseline/unitTestsBaseline.csv
@ibelem PTAL, thanks. 
This PR fixes build failure for #298 by CI.
=> [tool] Update baseline data of CI for WASM and WebGL2 backends supporting FC op.

examples/image_classification_onnx/main.js
=> [Example] Update params for new squeezenet model

examples/image_classification_tflite/ImageClassificationModel.js, examples/image_classification_tflite/TfLiteModelUtils.js, examples/image_classification_tflite/main.js, examples/image_classification_tflite/model/README.md, examples/image_classification_tflite/utils.js
- Support inception_v4 and inception_resnet_v2. 
- Update the Model reference in model/README.md due to the code refactor of https://github.com/tensorflow/tensorflow/commit/61c6c84964b4aec80aeace187aab8cb2c3e55a72
=> [Example] Support inception_v4 and inception_resnet_v2 and update model/README.md for image_classification_tflite  

src/nn/Model.js
passes: 307   failures: 179  duration: 9.67s
=> passes: 311  failures: 175  duration: 7.88s 
Fix #75
=> [WASM] Set the returned type of some Model methods to 'void' type

test/tools/CI/baseline/baseline.config.json, test/tools/CI/baseline/unitTestsBaseline.csv, test/tools/RegressionChecker/baseline/baseline.config.json, test/tools/RegressionChecker/baseline/unitTestsBaseline.csv
=> [tools] Update baseline datas for CI & RegressionChecker tools.

examples/image_classification_onnx/OnnxModelImporter.js, examples/image_classification_onnx/camera.html, examples/image_classification_onnx/index.html, examples/image_classification_onnx/main.js, examples/image_classification_onnx/utils.js, examples/image_classification_tflite/ImageClassificationModel.js, examples/image_classification_tflite/camera.html, examples/image_classification_tflite/index.html, examples/image_classification_tflite/main.js, examples/image_classification_tflite/utils.js, examples/posenet/camera.html, examples/posenet/camera.js, examples/posenet/index.html, examples/posenet/main.js, examples/posenet/src/PoseNet.js, examples/posenet/utils.js, examples/ssd_mobilenet/SsdMobileNet.js, examples/ssd_mobilenet/camera.html, examples/ssd_mobilenet/camera.js, examples/ssd_mobilenet/index.html, examples/ssd_mobilenet/main.js, examples/ssd_mobilenet/utils.js, examples/util/base.js
=>  [example] Support to switch preference options for example

.gitignore, examples/image_classification/main.js, examples/image_classification/model/README.md, examples/image_classification/utils.js, examples/util/onnx/OnnxModelImporter.js, examples/util/onnx/OnnxModelUtils.js
Fix #351
- add default value for the case of 'no padding'
- add Sum op for onnx
- update preprocess param
=> [Example] Support resnet50

.travis.yml
=> [tool] Fix Chrome installation failure by Travis-CI.

docs/api.md, docs/webml.idl, src/nn/Enums.js, src/nn/NeuralNetworkContext.js
=> [Polyfill] add ATROUS_CONV_2D AND ATROUS_DEPTHWISE_CONV_2D

src/nn/Enums.js
=> Fix the typo in Enums.js by replacing astrous with atrous.

test/cts/test/V1_0/resize_bilinear.js, test/cts/test/V1_0/resize_bilinear_2.js, test/cts/test/cts-all.js, test/cts/test_supplement/cts_supplement-all.js, test/cts/test_supplement/resize_bilinear_distorted_1.js, test/cts/test_supplement/resize_bilinear_distorted_2.js, test/cts/test_supplement/resize_bilinear_distorted_3.js, test/cts/test_supplement/resize_bilinear_distorted_4.js, test/cts/test_supplement/resize_bilinear_remain_size_1.js, test/cts/test_supplement/resize_bilinear_remain_size_2.js, test/cts/test_supplement/resize_bilinear_remain_size_3.js, test/cts/test_supplement/resize_bilinear_remain_size_4.js, test/cts/test_supplement/resize_bilinear_zoom_in_1.js, test/cts/test_supplement/resize_bilinear_zoom_in_2.js, test/cts/test_supplement/resize_bilinear_zoom_out_1.js, test/cts/test_supplement/resize_bilinear_zoom_out_2.js, test/cts/test_supplement/resize_bilinear_zoom_out_3.js, test/cts/test_supplement/resize_bilinear_zoom_out_4.js, test/cts/tool/CTSConverter/slice.txt, test/unit-test/test-Model.js
@ibelem PTAL, Thanks
This PR is to:
1. Add 17 Unit test cases and 16 CTS test cases to fix #342
2. Format **test/cts/test_supplement/cts_supplement-all.js** by **set ff=unix**
=> [test] Add test cases for RESIZE_BILINEAR op.

test/cts.html
The CDN takes long time for loading this test page in our network, use embeded style instead of external CDN link for css file.
@BruceDai please review.
=> [Test] Fix cts page loading issue

src/nn/webgl/WebGLModel.js
Fix https://github.com/intel/webml-polyfill/issues/337
=> [WebGL] support RESIZE_BILINEAR op

src/nn/webgl/WebGLModel.js
=> [WebGL] support atrous (depthwise) conv2d

examples/deeplab/main.js
=> [Example] capture video by default resolution and user facing mode

src/nn/webgl/WebGLModel.js
=> [WebGL] enable align_corner in RESIZE_BILINEAR

src/nn/wasm/PreparedModel.js
=> [WASM] support Atrous Conv2d/DepthwiseConv2d

benchmark/README.md, benchmark/index.html, benchmark/index.js, examples/deeplab/camera.html, examples/deeplab/index.html, examples/deeplab/main.js, examples/image_classification/camera.html, examples/image_classification/index.html, examples/image_classification/main.js, examples/image_classification/utils.js, examples/posenet/camera.html, examples/posenet/camera.js, examples/posenet/index.html, examples/posenet/main.js, examples/ssd_mobilenet/DrawOutputs.js, examples/ssd_mobilenet/camera.html, examples/ssd_mobilenet/camera.js, examples/ssd_mobilenet/index.html, examples/ssd_mobilenet/main.js, examples/ssd_mobilenet/utils.js, examples/util/base.js
This is PR is to:
1. Upgraded Benchmark test to support more image classification models. Fixes #310
2. Upgraded examples with Preference settings.
@huningxin @ibelem PTAL, Thanks.
=> [benchmark] Upgraded Benchmark test to support more image classification models.

package.json, src/nn/webgl/WebGLModel.js
=> Update tfjs-core version / Fix explicit padding bug of AVGPOOL

package.json
This version upgrade represents two developments:
1. Use tfjs-core ops to implement WebGL backend
2. Use tflite ops to implement WASM backend
Fix #413
=> [Polyfill] upgrade version to 0.0.2

src/nn/wasm/PreparedModel.js
=> [WASM] enable align_corner in RESIZE_BILINEAR

examples/deeplab/model/README.md
=> [Example] Fix mistake in DeepLab README

test/utils.js
=> [Test] support mkldnn backend

examples/posenet/src/PoseNet.js, examples/util/onnx/OnnxModelImporter.js, examples/util/tflite/TFliteModelImporter.js
=> [Example] Log compilation time

examples/util/tflite/TFliteModelImporter.js, src/nn/Enums.js, src/nn/wasm/PreparedModel.js, src/nn/webgl/WebGLModel.js
=> [API][Polyfill] support 'align_corners' in RESIZE_BILINEAR

examples/util/onnx/OnnxModelImporter.js, examples/util/tflite/TFliteModelImporter.js
Fix #349, #430, #431, #432, #433, #465
=> [Example] Fix onnx bugs on Android

examples/image_classification/index.html, examples/image_classification/main.js, examples/image_classification/ui.js, examples/index.html, examples/model.html, examples/static/css/style.css, examples/util/base.js, examples/util/uicommon.js
Fix #481 Object Detecion example link broken issue
Fix #482 live camera full screen toggle doesn't work issue
Fix #483 FPS number UI improvement
Fix #487 predictCamera doesn't stop when changing model
Add console.error back for exceptions in log
Replace function name with ES6 arrow function
=> [Image Classification] Fix #481 #482 #483 #487 and other improvements

examples/image_classification/main.js, examples/image_classification/ui.js, examples/image_classification/utils.js
=> [Example] improve state transition of util functions

webpack.config.js
=> [webpack] Source map for remote debugging

examples/image_classification/index.html, examples/image_classification/main.js, examples/image_classification/ui.js, examples/index.html, examples/model.html
[Image Classification] UE improvement: Set model=none by default to reduce unexpected MobileNetV1 loading at first time.
Users may don't need to load MobileNetV1 at all when visit the Image Classification page at first time, give them a choice and avoid 16.9MB model loading.
=> [Image Classification] UE improvement: Set model = none by default 

.filter-ci.js, .travis.yml
1. Check email format 
2. Check content contains sensitive fields
3. Check content contains network addr
@BruceDai PTAL
=> [CI] Check commit email/content contains sensitive fields

docs/supported_ops.md
Fix #523 
@ibelem , Please help to merge. Thanks!
=> update the native mapping of BNNS for add and mul

test/tools/RegressionChecker/baseline/baseline.config.json, test/tools/RegressionChecker/baseline/unitTestsBaseline.csv
=> [tool] Update baseline data for RegressionChecker toolkit by f8ebaa5.

examples/skeleton_detection/index.html, examples/skeleton_detection/main.js, examples/skeleton_detection/ui.js, examples/static/css/style.css
The initial guiState.scaleFactor value was updated to 0.75 during the testing, which should be set to 0.5 by default.
@huningxin PTAL
=> Fix #552 difficult to detect pose issue

examples/object_detection/camera.html, examples/object_detection/index.html, examples/util/base.js
@ibelem PTAL, Thanks
This PR is to modify button(id="selectPrefer") style and model names of Object Detection example.
=> [example] Updated Object Detection example

benchmark/index.html, benchmark/index.js, examples/util/base.js
@ibelem PTAL, Thanks.
This PR is to:
1. Upgrade Benchmark Test to support mklDNN backend and more Object Detection models.
2. Update Benchmark Test for existing Image Classification models and PoseNet model.
=> [benchmark] Upgraded Benchmark Test

benchmark/index.html, benchmark/index.js, examples/util/base.js
=> [benchmark] Fixed ReferenceError of Benchmark Test.

examples/util/onnx/OnnxModelImporter.js, examples/util/onnx/OnnxModelUtils.js
=> [Example] Support Flatten in ONNX

src/nn/webgl/WebGLModel.js
=> [WebGL] Support TANH op

package.json
=> [WebGL] upgrade tfjs-core version to 0.15.4

examples/image_classification/index.html, examples/index.html, examples/model.html, examples/object_detection/index.html, examples/semantic_segmentation/index.html, examples/semantic_segmentation/ui.js, examples/skeleton_detection/index.html
[Example] Image Classification position and refine canvas size for Semantic Segmentation
1. Put Image Classification to first in home page
2. Update Image Classification to first item in navigation 
3. Expand the canvas size properly for Semantic Segmentation
@huningxin @pinzhenx @Wenzhao-Xiang PTAL
https://ibelem.github.io/webml-website/examples/semantic_segmentation/index.html
=> [Example] Image Classification position and refine canvas size

examples/semantic_segmentation/model/README.md
=> [Example] Update DeepLab README

examples/object_detection/main.js, examples/object_detection/utils.js, examples/semantic_segmentation/main.js, examples/semantic_segmentation/utils.js
=> [Example] Improve state transition of obj detect and deeplab

examples/image_classification/main.js, examples/image_classification/ui.js
@pinzhenx @Wenzhao-Xiang PTAL.
@huningxin may have no time for reviewing PRs from tomorrow this week.
=> [Example] Aviod Recompile model for Image Classification

test/tools/RegressionChecker/baseline/baseline.config.json, test/tools/RegressionChecker/baseline/unitTestsBaseline.csv
=> [tool] Update baseline data with build b3ad1c0.

examples/object_detection/utils.js
=> [Example] Abort download in object detection

benchmark/README.md, benchmark/index.html, benchmark/index.js, examples/util/base.js
=> [benchmark] Upgrade Benchmark test by adding Semantic Segmentation models and Tiny Yolo v2 models.

examples/util/decoders/SsdDecoder.js, examples/util/decoders/Yolo2Decoder.js
=> Update color for objection detection in decoders

examples/skeleton_detection/main.js, examples/skeleton_detection/ui.js
Test URL: https://ibelem.github.io/webml-website/examples/skeleton_detection/
Fix #647 
@Wenzhao-Xiang @pinzhenx PTAL
=> Aviod recompile model for Skeleton Detection

src/nn/webgl/WebGLModel.js
Fix #614 , fix #612 . 
@huningxin @Wenzhao-Xiang @pinzhenx , PTAL, thanks.
=> [WebGL] support batchToSpace and transpose

test/cts/test/V1_0/tanh.js, test/cts/test/V1_0_plus/maximum.js, test/cts/test/V1_0_plus/maximum_4d.js, test/cts/test/V1_0_plus/maximum_compatible.js, test/cts/test/cts-all.js, test/unit-test/test-Model.js
Add 30 test cases for "TANH" and "MAXIMUM" op:
op | cts | plus | test-Model.js
---- | ---- | ---- | ----
TANH | 1 | 0 | 12
MAXIMUM | 0 | 3 | 14
Fix: #610 and #580
=> [test] Add test cases for "TANH" and "MAXIMUM" op

test/unit-test/test-Model.js
Impacted tests: new 23, update 0, delete 0 
Update unit test cases for coverage missing with Ming and @BruceDai PTAL, Thanks.
=> [TEST]Update unit test cases for coverage missing

src/nn/Execution.js, src/nn/Model.js, src/nn/wasm/PreparedModel.js, src/nn/webgl/WebGLModel.js
This PR is to: 
1. Fixed some issues of boundary value.             
2. Removed some invalid default codes of switch blocks since those exceptions are checked to throw error before.
@Wenzhao-Xiang @GreyZzzzzzXh Please help review those modifications, thanks.
=> [WASM/WebGL] Fixed some issues of boundary value.

test/tools/RegressionChecker/baseline/baseline.config.json, test/tools/RegressionChecker/baseline/unitTestsBaseline.csv
=> [tool] Update baseline data with build a7c5589

test/cts/test/V1_1/batch_to_space.js, test/cts/test/V1_1/batch_to_space_float_1.js, test/cts/test/V1_1/transpose.js, test/cts/test/V1_1/transpose_float_1.js, test/cts/test/cts-all.js, test/unit-test/test-Model.js
Add 37 test cases for "BATCH_TO_SPACE_ND" and "TRANSPOSE" op:
op | cts | plus | test-Model.js
-- | -- | -- | --
BATCH_TO_SPACE_ND | 2 | 0 | 16
TRANSPOSE | 2 | 0 | 17
Fix: #579 and #581 
=> [test] Add test cases for 'BATCH_TO_SPACE_ND' and 'TRANSPOSE' op

benchmark/index.html, benchmark/index.js, examples/image_classification/index.html, examples/image_classification/main.js, examples/image_classification/ui.js, examples/image_classification/utils.js, examples/object_detection/index.html, examples/object_detection/main.js, examples/object_detection/ui.js, examples/object_detection/utils.js, examples/semantic_segmentation/index.html, examples/semantic_segmentation/main.js, examples/semantic_segmentation/ui.js, examples/semantic_segmentation/utils.js, examples/skeleton_detection/index.html, examples/skeleton_detection/main.js, examples/skeleton_detection/src/PoseNet.js, examples/skeleton_detection/ui.js, examples/skeleton_detection/utils.js, examples/static/css/style.css, examples/util/base.js, examples/util/onnx/OnnxModelImporter.js, examples/util/tflite/TFliteModelImporter.js, src/nn/Compilation.js, src/nn/Enums.js, src/nn/GraphUtils.js, src/nn/Model.js, src/nn/utils.js, src/nn/wasm/PreparedModel.js, src/nn/webgl/WebGLModel.js
=> [Polyfill] Allow to offload to WebNN backend

test/end2end-test/README.md, test/end2end-test/end2end_test-all.js, test/end2end-test/test_inception_v2_onnx.js, test/end2end-test/test_mobilenetv2-1.0_onnx.js, test/end2end-test/test_resnet50v1_onnx.js, test/end2end-test/test_resnet50v2_onnx.js, test/end2end-test/test_squeezenet1.1_onnx.js, test/utils.js
=> Update README file of end2end test

examples/semantic_segmentation/index.html, examples/semantic_segmentation/src/DrawOutputs.js, examples/semantic_segmentation/ui.js, examples/static/css/style.css
=> [Example] UI Enhancement of DeepLab

benchmark/README.md, benchmark/index.html, benchmark/index.js, examples/util/base.js
=> [benchmark] Upgraded Benchmark test to support two quantized models

test/tools/RegressionChecker/README.md, test/tools/RegressionChecker/package.json
=> [tool] Update chromedriver version for chromium 75 and README

test/tools/RegressionChecker/baseline/baseline.config.json, test/tools/RegressionChecker/baseline/unitTestsBaseline.csv
=> [tool] Update baseline data with build c623981

examples/util/onnx/OnnxModelImporter.js, examples/util/onnx/OnnxModelUtils.js, examples/util/tflite/TFliteModelImporter.js, src/nn/wasm/PreparedModel.js, src/nn/webgl/WebGLModel.js
=> [Polyfill/Example] Fix typo of error message

examples/facial_landmark_detection/main.js, examples/skeleton_detection/ui.js
=> [Example] Bug fixes in Posenet and Facial Landmark

examples/skeleton_detection/ui.js
=> [Example] Fix bug in Posenet options

examples/facial_landmark_detection/index.html, examples/facial_landmark_detection/main.js, examples/image_classification/index.html, examples/image_classification/main.js, examples/object_detection/index.html, examples/object_detection/main.js, examples/semantic_segmentation/index.html, examples/semantic_segmentation/main.js, examples/skeleton_detection/index.html, examples/skeleton_detection/main.js, examples/static/css/style.css, examples/static/js/ui.common.js, examples/super_resolution/index.html, examples/super_resolution/main.js
- Add Subgraphs UI when select dual backends
- Simplify title (e.g. FAST_SINGLE_ANSWER -> FAST) since the title is too long now
- Enhance the tooltip when selecting backends in case stakeholders ask baclends relevant questions again 
@Wenzhao-Xiang @pinzhenx @huningxin PTAL
https://ibelem.github.io/webml-website/examples/
=> [Example] Add subgraphs ui support

test/cts/test_supplement/atrous_depthwise_conv2d_same.js, test/cts/test_supplement/cts_supplement-all.js, test/unit-test/test-Model.js
=> [test] Allocate Uint8Array for TENSOR_QUANT8_ASYMM type

test/cts/test_supplement/cts_supplement-all.js, test/cts/tool/CTSConverter/src/main.py
=> Add describe for CTS supplement

benchmark/index.js
=> [benchmark] Updated test with Semantic Segmentation Models

test/tools/RegressionChecker/README.md, test/tools/RegressionChecker/config.json, test/tools/RegressionChecker/src/main.js
1. Support inference engine
2. Can be tested separately to webml-polyfill and webml-nn
Fix: #668 #710 
=> Support inference engine and can be tested separately to webml-polyfill and webnn

LICENSE, examples/third_party/dat.gui.js
Apache 2.0 Licensing Conditions:
- In every licensed file changed, a notification must be added stating that changes have been made to that file.
@pinzhenx @Wenzhao-Xiang PTAL
=> [License] Add modification notification for Apache 2.0 file

examples/object_detection/model/LICENSE, examples/object_detection/model/README.md
Now, use the model converted by myself to avoid the license issue.
@ibelem  Please help take a look! Thanks!
=> [Example] update tiny_yolov2_coco model and add license for label files

test/tools/CI/baseline/baseline.config.json, test/tools/CI/baseline/unitTestsBaseline.csv
=> Update CI baseline data with build ef9d267

test/realmodel/src/generateCase.js
=> [test] Fix input1 tensor setting issue of Reshape testcase for realmodel.

package.json
=> [tool] Upgrade chromedriver version to 2.46.0 for travis ci.

test/unit-test/test-Compilation.js, test/unit-test/test-Execution.js, test/unit-test/test-Model.js, test/utils.js
@ibelem This PR updated 15 Unit Test Cases for aysnc method. PTAL, thanks
=> [test] Updated exception checking for aysnc method.

test/utils.js
@ibelem This test case PR is related to fix #744. PTAL, thanks
=> [test] Changed test URL with 'prefer' parameter.

.circleci/config.yml
=> [tool] Upgraded docker image to circleci/node:12.1.0-browsers.

benchmark/index.js, src/nn/wasm/PreparedModel.js, src/nn/webgl/WebGLModel.js
=> [Polyfill][Benchmark] expose profiling results

examples/util/onnx/OnnxModelUtils.js
Fix #784 
- Eliminate unnecessary data copy to prevent GC
- Reduce the init time of Resnet ONNX by ~5x
=> [Example] Optimize ONNX Importer

examples/util/onnx/OnnxModelImporter.js, examples/util/onnx/OnnxModelUtils.js
https://github.com/intel/webml-polyfill/issues/777
=> [ONNX] Support Transpose & Neg & general concat

test/tools/RegressionChecker/src/main.js
=> [tool] Log off prefer 'Win-WebNN-Low-DML' to wait for function realization

test/tools/RegressionChecker/src/main.js
=> [test] Remove unnecessary spaces for test case name

README.md
Reverts intel/webml-polyfill#824
=> Revert "[README] Resize QR Code"

benchmark/index.html, benchmark/main.js, benchmark/ui.js, benchmark/utils.js, benchmark/utils_fld.js
=> [benchmark] Add facial landmark detection

benchmark/index.html, benchmark/main.js, benchmark/ui.js, benchmark/utils.js, benchmark/utils_ic.js, benchmark/utils_sr.js, benchmark/utils_ss.js
=> [benchmark] Add super resolution

src/nn/webgl/WebGLModel.js
@pinzhenx, PTAL, thanks. 
fix #813
=> [WebGL] fix memory leak

benchmark/index.html, benchmark/main.js, benchmark/ui.js, benchmark/utils_ea.js, benchmark/utils_em.js
add emotion_analysis code in benchmark
=> [benchmark]add emotion_analysis code in benchmark

benchmark/utils_ea.js, benchmark/utils_fld.js
Fix bug to support benchmark test. Btw, I will update benchmark use "canvas" later.
@BruceDai PTAL.
=> [benchmark] Fix bug of facial landmark detection

package.json
=> [WebGL] upgrade tfjs-core version to 1.2.2

examples/emotion_analysis/main.js, examples/facial_landmark_detection/main.js, examples/image_classification/main.js, examples/object_detection/main.js, examples/semantic_segmentation/main.js, examples/skeleton_detection/README.md, examples/skeleton_detection/main.js, examples/skeleton_detection/model/README.md, examples/skeleton_detection/src/helperFunc.js, examples/static/js/ui.common.js, examples/super_resolution/main.js
1. Update the stepper words simpler
2. Update the posenet model download issue since 404 from https://storage.googleapis.com/tfjs-models/weights/posenet/mobilenet_v1_101/manifest.json now
@Wenzhao-Xiang @BruceDai PTAL
=> [example] Stepper UI words change

examples/semantic_segmentation/main.js
Sorry for the regression. @pinzhenx PTAL
=> [Example] Fix Semantic Segmentation Camera display issue

test/tools/RegressionChecker/src/main.js
=> [test] Add enviroment for backend MKLDNN on Mac OS

benchmark/README.md, benchmark/resources/utils_sd.js, examples/skeleton_detection/src/helperFunc.js
=> [benchmark] Adjust model files path for Skeleton Detection of Benchmark Test.

docs/supported_ops.md
@ibelem, @huningxin, @fujunwei, @lisa0314, @Wenzhao-Xiang, PTAL.
=> [docs] Update supported_ops.md

test/tools/RegressionChecker/config.json, test/tools/RegressionChecker/package.json, test/tools/RegressionChecker/src/main.js
=> [test] Update RC tool using 'cheerio' module to analyze HTML file

.circleci/config.yml
Update the config file base on [Circle CI configuration-reference](https://circleci.com/docs/2.0/configuration-reference/#branches).
> branches
> Defines rules for whitelisting/blacklisting execution of some branches if Workflows are not configured and you are using 2.0 (not 2.1) config. If you are using Workflows, job-level branches will be ignored and must be configured in the Workflows section of your config.yml file. 
@BruceDai @miaobin @shenx3x PTAL
=> [CI] Update Circle CI config file

test/cts/test/cts-all.js, test/cts/test_supplement/cts_supplement-all.js, test/cts/tool/CTSConverter/src/main.py
=> [test] Reset timeout to run CTS test cases for CTS tool

examples/static/css/style.css
=> Fix #938 Front-facing camera display issue

examples/speech_commands/main.js
@belem @BruceDai @Christywl I have fixed the record issue of Speech Commands.
PTAL, thanks!
=> [Example] Speech Commands record optimize

test/tools/RegressionChecker/README.md, test/tools/RegressionChecker/config.json, test/tools/RegressionChecker/src/main.js
=> [test/tool] Enable regression checker tool to check real model

examples/emotion_analysis/index.html, examples/facial_landmark_detection/index.html, examples/image_classification/index.html, examples/index.html, examples/model.html, examples/object_detection/index.html, examples/semantic_segmentation/index.html, examples/simple/index.html, examples/skeleton_detection/index.html, examples/speech_commands/index.html, examples/super_resolution/index.html
=> [Example] Add Google Analytics

test/realmodel/src/generateCase.js, test/realmodel/src/genhtml.js, test/tools/perLayerAnalyzer/src/gethtml.js
=> [test] Added  the ADD operator test in realmodel testcase

test/realmodel/src/generateCase.js
=> [test] Added the DEPTHWISE_CONV_2D ops test in realmodel testcase

workload/resources/main.js, workload/resources/utils.js, workload/resources/utils_ea.js, workload/resources/utils_fld.js
=> [workload] Fixed some errors when loading model files.

test/cts/test/V1_0_plus/maximum.js, test/cts/test/V1_0_plus/maximum_4d.js, test/cts/test/V1_0_plus/maximum_compatible.js, test/cts/test/cts-all.js
=> [test] Fix input for 'MAXIMUM' test case

docs/api.md
Add PRELU op into [api doc](https://github.com/intel/webml-polyfill/blob/master/docs/api.md) and has been implemented by #982.
fixes #1023 
=> [doc] Add PRELU op

package.json
=> [ci] Upgrade chromedriver version to 77.0.0 to support Chrome 78.

.circleci/config.yml
=> [ci] Upgraded circleci using node:12.9.1-browser image to align with chromedriver 77.0.0.

test/cts/test_supplement/argmax_2d_axis_0.js, test/cts/test_supplement/argmax_2d_axis_1.js, test/cts/test_supplement/argmax_3d_axis_2.js, test/cts/test_supplement/argmax_4d_axis_3.js, test/cts/test_supplement/cts_supplement-all.js
=> [test] Add some ARGMAX CTS tests.

test/unit-test/test-Model.js
Add 45 unit test cases for "LOGISTIC" and "PRELU" op:
op | test-Model.js
-- | -- 
LOGISTIC | 18
PRELU | 27
fixes #1039 and fixes #1040
=> [test] Add unit test cases for LOGISTIC and PRELU ops

examples/util/base.js
=> [example] Update base.js file to support facenet model

examples/face_recognition/model/README.md
=> [example] Update google URL of facenet.bin file

test/realmodel/index.html, test/realmodel/package.json, test/realmodel/src/generateCase.js
=> [test] PerLayerAnalyzer of Resnet50v1 and Resnet50v2 in realmodel test

test/realmodel/src/getCaseOriginData.js
=> [test]Add more wait time in order to generate resnet50v json file

test/cts/test/V1_0_plus/prelu_quant8_1.js, test/cts/test/V1_0_plus/prelu_quant8_2.js, test/cts/test/cts-all.js, test/cts/test_supplement/cts_supplement-all.js, test/cts/test_supplement/prelu_quant8_broadcasting_2d.js, test/cts/test_supplement/prelu_quant8_broadcasting_3d.js, test/cts/test_supplement/prelu_quant8_broadcasting_4d.js
=> [test] Update quant8 data for PRELU test cases

test/unit-test/test-Model.js
Add 32 unit test cases for "ARGMAX" op:
op | test-Model.js
-- | -- 
ARGMAX | 32
fixes #1057
=> [test] Add unit test cases for ARGMAX op

examples/util/openvino/OpenVINOModelImporter.js, examples/util/openvino/OpenVINOModelUtils.js
1. Support **Normalize** and **PReLU** and **Activation** ops.
2. Implement Int32 data type.
3. Recode **Permute** ops.
4. Fix none-value and dims-value bugs for **FullyConnected** op.
fixes #1002 and fixes #1006
=> [openvino] Support PReLU and Activation ops

package.json
=> [ci] Upgraded chromedriver version to be 78.0.1.

test/realmodel/README.md, test/tools/perLayerAnalyzer/README.md
=> [test] Add descriptions of resnet50V1 and resnet50V2 in README.md files

examples/semantic_segmentation/model/README.md, examples/semantic_segmentation/src/DrawOutputs.js, examples/semantic_segmentation/utils.js, examples/util/base.js, examples/util/tflite/TFliteModelImporter.js, workload/index.html, workload/resources/utils_ss.js
This PR involves:
1. Upgraded Deeplab models with supported ARGMAX Op for example and workload.
2. Added supported ops by DirectML into mapping table of examples/util/base.js.
@huningxin @pinzhenx @fujunwei  @ibelem  PTAL, thanks
=> [example][workload] Upgraded Deeplab models with supported ARGMAX Op

examples/emotion_analysis/index.html, examples/face_recognition/index.html, examples/facial_landmark_detection/index.html, examples/image_classification/index.html, examples/index.html, examples/model.html, examples/object_detection/index.html, examples/semantic_segmentation/index.html, examples/skeleton_detection/index.html, examples/speech_commands/index.html, examples/super_resolution/index.html
=> [examples] add navigation links for Face Recognition

package.json, src/nn/webgl/WebGLModel.js
Close[#1048](https://github.com/intel/webml-polyfill/issues/1048)
=> [WebGL]Upgrade TF.js to v1.2.11

examples/static/js/ui.common.js
=> Fix #1077 MPS badge issue

examples/face_recognition/main.js
Fix #1098
@cuiyanx  PTAL. @BruceDai @Christywl
=> [example] fix face recognition inference time issue

examples/face_recognition/README.md, examples/face_recognition/utils.js, examples/util/base.js
1. Describe model detail information, add reference of threshold value(1.26/0.8) in README。
2. Add model attribute '**postOptions**'.
3. Rename function names and add **sqrt** method for **euclideanDistance** function.
4. Optimize code block by model attribute '**postOptions.distanceMetric**' as **euclidean** or **cosine**. 
5. Add comment for ‘X’  that is default status '**unknown**'.
=> [example] Update face recognition

examples/util/openvino/OpenVINOModelImporter.js
fix https://github.com/intel/webml-polyfill/issues/1108
=> [OpenVINO] convert weights and bias of scaleshift to 4D tensor

test/tools/RegressionChecker/package.json, test/tools/RegressionChecker/src/main.js
=> [test/tool] Update regression checker tool to support chromium 79

test/tools/RegressionChecker/baseline/baseline.config.json
=> [tool] Update the versions of baseline.config.json

docs/supported_ops.md
=> [Doc] Update supported_ops based on the latest build ee68e8f

test/tools/RegressionChecker/README.md, test/tools/RegressionChecker/config.json, test/tools/RegressionChecker/src/main.js
=> [tool] Update RegressionChecker tool to support IE and GNA

test/tools/RegressionChecker/src/main.js
=> Shield 'low-DML' backend for windows

examples/util/BaseExample.js
This PR is to fix memory free issue of double clicking same polyfill backend.
@ibelem @huningxin PTAL, thanks
=> [example] Fixed memory issue for using polyfill backend.

docs/api.md, docs/webml.idl, src/nn/Enums.js, test/utils.js
@huningxin @fujunwei @ibelem PTAL, thanks
So we will use 
```javascript
<url>?prefer=ultra-low
```
to test with GNA plugin @Christywl  @mingmingtasd @miaobin
=> [doc][test] Support a new preference code 'ULTRA_LOW_POWER' for testing GNA plugin.

.gitignore, examples/speech_recognition/README.md, examples/speech_recognition/SpeechRecognitionExample.js, examples/speech_recognition/SpeechRecognitionRunner.js, examples/speech_recognition/ark/README.md, examples/speech_recognition/index.html, examples/speech_recognition/main.js, examples/speech_recognition/model/README.md, examples/static/css/style.css, examples/static/js/ui.common.js, examples/util/base.js, examples/util/modelZoo.js, examples/util/openvino/OpenVINOModelImporter.js
Update the example based on #1181 
@Christywl Please help test the new example. 
@ibelem @fujunwei @mingmingtasd ming @BruceDai PTAL, thanks!
=> [Example] Add Speech Recognition

examples/face_recognition/FaceRecognitionExample.js
@ibelem This PR fixed #1226, PTAL and help merge it, then we could upgrade github page, thanks.
=> [example] Fixed incorrect inference result with Tiny Yolo v2 Face model for Face Recognition example.

src/nn/wasm/PreparedModel.js
=> [WASM] Make TRANSPOSE support tensor less than 4D

src/nn/wasm/PreparedModel.js
=> [WASM] Transpose less than 4D debug

package.json
=> [WASM] Use fixed version of tfjs-backend-wasm.

examples/speech_recognition/SpeechRecognitionExample.js
@miaobin @fujunwei  Please help to review, thanks!
=> [example] Define the threshold value for GNA in particular

README.md, examples/static/js/ui.common.js
I think it's time to have more introduction for our project in readme, especially @huningxin and anssi are leading the spec edit and pushing the cg to wg. PTAL @huningxin @BruceDai @fujunwei @lisa0314 @mingmingtasd 
Maybe I should remove "# Web Machine Learning" but our repo name is still webml-polyfill rather than webnn-polyfill.
=> Update project summary in readme

examples/image_classification/README.md, examples/image_classification/index.html, examples/static/css/style.css, examples/static/js/ui.common.js, examples/util/BaseExample.js
@BruceDai PTAL and check if it's necessary.
=> [Example] Add flag notes for SIMD and Threads

examples/semantic_segmentation/index.html, examples/semantic_segmentation/model/README.md, examples/util/modelZoo.js, examples/util/openvino/OpenVINOModelImporter.js
- Add OpenVINO IR format model for Semantic Segmentation
- Support atrous convolution, Interp and Argmax in OpenVINOModelImporter.js.
@BruceDai @fujunwei @mingmingtasd , PTAL.
Thanks.
=> [Example] Add OpenVINO model for Semantic Segmentation

examples/util/BaseExample.js
=> [WASM] Fix the memory issue of tfjs-wasm-backend.

examples/image_classification/index.html, examples/image_classification/model/README.md, examples/util/BaseExample.js, examples/util/WebNNRunner.js, examples/util/caffe2/Caffe2.js, examples/util/caffe2/Caffe2ModelImporter.js, examples/util/caffe2/Caffe2ModelUtils.js, examples/util/modelZoo.js
Add caffe2 model importer and squeezenet model
=> [example] Add caffe2 model importer and squeezenet model

examples/image_classification/model/README.md
@cuiyanx @ibelem PTAL, thanks.
=> [examples] Updated Caffe2 models' links in README.md of Image Classification example.

tsconfig.json, webpack.config.js
=> Don't emit and generate ts files

workload/index.html
Support Caffe2 model for WebNN workload.
@BruceDai PTAL, thanks.
=> [Workload] Support Caffe2 model for workload

workload/resources/OpenCVExecutor.js, workload/resources/WebNNExecutor.js
@huningxin @ibelem @lisa0314 PTAL, Thanks.
=> [workload] Removed progress animation to get correct performance data.

examples/util/BaseCameraExample.js, examples/util/BaseExample.js, examples/util/BaseMircophoneExample.js, examples/util/base.js
@huningxin @ibelem PTAL, thanks.
=> [examples] Added workaround for {facingMode: 'environment'} not working on Note10+ phone.

examples/emotion_analysis/EmotionAnalysisExample.js, examples/face_recognition/FaceRecognitionExample.js, examples/facial_landmark_detection/FacialLandmarkDetectionExample.js, examples/util/BaseExample.js, examples/util/BaseRunner.js, examples/util/OpenCVRunner.js, examples/util/WebNNRunner.js, examples/webnnmeeting/assets/js/webnn/util/BaseRunner.js, examples/webnnmeeting/assets/js/webnn/util/WebNNRunner.js
=> [examples] Fixed label result by MobileNetv1 Quant(caffe2).

examples/webnnmeeting/assets/js/webnn/util/BaseRunner.js
=> [webnnmeeting] Fix lack of initialization issue

src/nn_v2/NeuralNetworkContext.ts
=> [api] Fixed type issue of importing MatMul of nn v2.

workload/resources/BaseExecutor.js, workload/resources/EmotionAnalysisWebNNExecutor.js, workload/resources/FacialLandmarkDetectionWebNNExecutor.js, workload/resources/SkeletonDetectionWebNNExecutor.js, workload/resources/Workload.js
@huningxin @ibelem PTAL, thanks.
=> [workload] Initialize runner for workload.

package.json, src/nn/tfjs/TfjsModel.js
=> Upgrade tfjs to 2.0.1

examples/semantic_segmentation/SemanticSegmentationExample.js, examples/semantic_segmentation/SemanticSegmentationOpenCVRunner.js, examples/semantic_segmentation/index.html, examples/semantic_segmentation/model/README.md, examples/static/js/ui.common.js, examples/util/OpenCVRunner.js, examples/util/modelZoo.js
=> [example] Enhance semantic segmentation example with OpenCV.js

workload/index.html, workload/resources/ImageClassificationOpenCVExecutor.js, workload/resources/ImageClassificationWebNNExecutor.js, workload/resources/SemanticSegmentationWebNNExecutor.js, workload/resources/Workload.js
Current I'm implementing automation testing workload toolkit, add Top3 result (label and probability) of Image Classification for checking regression.
@huningxin @ibelem PTAL, thanks.
=> [workload] Showed Top3 result (label and probability) of Image Classification on UI.

examples/util/OpenCVRunner.js
@ibelem @akineeic @miaobin PTAL, thanks.
The result image likes:
And I also verified Image Classification using OpenCV.js, the results are OK, not impacted by this PR, thanks.
=> [example] Fixed the issue of incorrect colorized person with OpenCV.js for Semantic Segmentation.

.circleci/config.yml, package.json
=> [ci] Update CI using chromedriver of 85.0.0.

package.json, src/nn/Compilation.js, src/nn/Model.js, src/nn/NeuralNetworkContext.js, src/nn/tfjs/TfjsModel.js
Currently WebGPU backend only works with enabled 'Unsafe WebGPU' flags on Windows and macOS platform, it would block us by issue #1346, so we reverted this WebGPU backend implement.
@huningxin @ibelem  PTAL, thanks.
=> [webgpu] Reverted WebGPU backend implement.

test/tools/workload-toolkit/package.json, test/tools/workload-toolkit/util/compare-result.js, test/tools/workload-toolkit/util/run-test.js
=> [tool] Use playwright-chromium library instead of playwright for optimization of installation.

test/utils.js
@ibelem @fujunwei @mingmingtasd PTAL, thanks.
=> [test] Fixed issue of set 'prefer' var in setOptions function.

README.md, workload/opencv_threshold/css/style.css, workload/opencv_threshold/index.html, workload/opencv_threshold/perf_threshold.html, workload/opencv_threshold/perf_threshold_simd.html, workload/opencv_threshold/perf_threshold_thread.html, workload/opencv_threshold/perf_threshold_thread_simd.html
@huningxin @BruceDai PTAL
@huningxin Do you think we should add the workload links in README?
=> Add workload entrance in README

examples/emotion_analysis/index.html, examples/face_recognition/index.html, examples/facial_landmark_detection/index.html, examples/image_classification/index.html, examples/image_classification_opencv/index.html, examples/index.html, examples/model.html, examples/object_detection/index.html, examples/semantic_segmentation/index.html, examples/skeleton_detection/index.html, examples/speech_commands/index.html, examples/speech_recognition/index.html, examples/static/js/model.js, examples/style_transfer/README.md, examples/style_transfer/StyleTransferExample.js, examples/style_transfer/index.html, examples/style_transfer/main.js, examples/style_transfer/model/README.md, examples/super_resolution/index.html
@miaobin PTAL then fix legacy video relevant issue.
=> Update Example for Style Transfer

examples/semantic_segmentation/index.html, examples/util/modelZoo.js
=> [Semantic Segmentation] Fix undefined protobuf issue

examples/image_classification/model/README.md, examples/util/WebNNRunner.js, examples/util/modelZoo.js
Supported these three quantized models now and uploaded them to [google drive](https://drive.google.com/drive/folders/1hkrHRV7bI66GRMYZ26hhEqq5mxt-TdPt?usp=sharing). PTAL, thanks! @BruceDai @ibelem @lisa0314
=> [example] Support mobilenet_v1/v2 and resnet50_v1 int8 OpenVINO models

package.json, test/tools/RegressionChecker/package.json, test/tools/perLayerAnalyzer/package.json, test/tools/workload-toolkit/package.json
fixes #1387
@ibelem PTAL, thanks.
=> Fixed security issue by updated fast-csv to 4.3.6.

workload/resources/Workload.js
Fix #1386. Now the results contain both average inference data metrics and median inference data metrics in workload.
=> Add median inference data metrics for workload

examples/util/BaseRunner.js, examples/util/WebNNRunner.js, examples/webnnmeeting/assets/js/webnn/util/BaseRunner.js, examples/webnnmeeting/assets/js/webnn/util/WebNNRunner.js
=> [example] Fixed reloading model issue when changing backend.

package.json
=> Updated tf.js to 2.8.5.

README.md
=> Adding deprecated message and new repo links

examples/emotion_analysis/index.html, examples/face_recognition/index.html, examples/facial_landmark_detection/index.html, examples/image_classification/index.html, examples/index.html, examples/model.html, examples/object_detection/index.html, examples/semantic_segmentation/index.html, examples/skeleton_detection/index.html, examples/speech_commands/index.html, examples/speech_recognition/index.html, examples/style_transfer/index.html, examples/super_resolution/index.html
=> [Example] update year to 2021 in page footer

workload/index.html, workload/resources/Workload.js
=> Add steps of running OpenCV Workload on page.
