docs/supported_ops.md, src/nn/Enums.js, test/index.html, test/operations/add.js, test/operations/avg_pool_2d.js, test/operations/concatenation_0.js, test/operations/concatenation_1.js, test/operations/concatenation_2.js, test/operations/concatenation_3.js, test/operations/concatenation_neg1.js, test/operations/max_pool_2d.js, test/operations/mul.js, test/operations/reshape.js, test/operations/reshape_neg1.js, test/operations/softmax.js, test/unit-test/test-Compilation.js, test/unit-test/test-Execution.js, test/unit-test/test-Model.js, test/utils.js
Accoring to [ANEURALNETWORKS_DEPTHWISE_CONV_2D](https://developer.android.com/ndk/reference/group/neural-networks#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0a2b49a44b7ebba243fad01556c1f0392e) explanation in Android NN API document, I updated 
> Inputs (explicit padding):
to be
> Inputs (**implicit** padding):
for the comments of **DEPTHWISE_CONV_2D** in src/nn/Enums.js
Referring to **concatenation** and **reshape** methods of tensorflow in python version, I wrote some tests  in the test/operations folder for concatenation and reshape operations.
Use **window.onload** event to prepare options for createModel function, then we cloud run unit tests
using Web ML Polyfill API with **WebGL2 backend** by visit such url:
> http://\<domain-name\>/test/index.html?backend=webgl2 …
=> [test] Add unit tests and also enable to run unit tests using WebGL2 backend.

examples/mobilenet/MobileNet.js
Signed-off-by: Belem Zhang <belem.zhang@intel.com>
Fix https://github.com/intel/webml-polyfill/issues/101 
MobileNet.js: 
Line 126:      let opCode = this._tfModel.operatorCodes(operator.opcodeIndex()).builtinCode();
Line 193:           throw new Error(`operator type ${opcode} is not supported.`);
The ${opcode} causes following error in throw new Error() statement:
Uncaught (in promise) ReferenceError: **opcode** is not defined
at MobileNet._addOpsAndParams (MobileNet.js:193)
Update variable name from "opcode" to 'opCode' declared in Line 126 can fix this issue.
=> Fix case-sensitive variable name issue in MobileNet.js

src/nn/webgl2/layers/pooling/_Pool2D.js
This bug occurs in pooling layer whose `padding === 'SAME'`.
=> [WebGL2] Fix a padding error in pool2D

src/nn/webgl2/Model.js, src/nn/webgl2/Tensor.js
Fix #142 #214 
_MAX_TEXTURE_IMAGE_UNITS_ is not used in Keras.js, let's just remove it.
=> [WebGL2][PoseNet] Support scale factor = 1

src/nn/webgl2/webgl/fragmentShader/activation/RELU1.js, src/nn/webgl2/webgl/fragmentShader/activation/fuse.js
passes: _**91**_  failures: _**14**_  duration: _**2.67**_ s
=> passes: _**101**_  failures: _**4**_  duration: _**2.82**_ s
fix #272
=> [WebGL2] Correct the output range of RELU1 to [-1, 1]

test/cts/test/V1_0/fully_connected_float.js, test/cts/test/V1_0/fully_connected_float_2.js, test/cts/test/V1_0/fully_connected_float_large.js, test/cts/test/V1_0/fully_connected_float_large_weights_as_inputs.js, test/cts/test/V1_0/fully_connected_float_weights_as_inputs.js, test/cts/test/V1_0_plus/add_relu.js, test/cts/test/V1_0_plus/add_relu1.js, test/cts/test/V1_0_plus/add_relu6.js, test/cts/test/V1_0_plus/avg_pool_float_1_relu.js, test/cts/test/V1_0_plus/avg_pool_float_1_relu1.js, test/cts/test/V1_0_plus/avg_pool_float_1_relu6.js, test/cts/test/V1_0_plus/fully_connected_float_relu.js, test/cts/test/V1_0_plus/fully_connected_float_relu1.js, test/cts/test/V1_0_plus/fully_connected_float_relu6.js, test/cts/test/V1_0_plus/max_pool_float_1_relu.js, test/cts/test/V1_0_plus/max_pool_float_1_relu1.js, test/cts/test/V1_0_plus/max_pool_float_1_relu6.js, test/cts/test/V1_0_plus/mul_relu1.js, test/cts/test/V1_0_plus/mul_relu6.js, test/cts/test/cts-all.js, test/cts/test_supplement/cts_supplement-all.js, test/cts/test_supplement/fully_connected_float_1d.js, test/cts/test_supplement/fully_connected_float_3d.js, test/cts/test_supplement/fully_connected_float_3d_2.js, test/cts/test_supplement/fully_connected_float_4d.js
@huningxin @ibelem PTAL, thanks
Those 5 test case in test/cts/test/V1_0 folder were converted from Android CTS, others 18 test cases were designed by myself.
According to following [explanations of FULLY_CONNECTED op](https://github.com/intel/webml-polyfill/blob/master/src/nn/Enums.js#L459),
```
* Supported tensor rank: up to 4.
*
* Inputs:
* * 0: A tensor, specifying the input. If rank is greater than 2, then it gets flattened to
*      a 2-D Tensor. The 2-D Tensor is handled as if dimensions corresponded to shape
*      [batch_size, input_size]
```
here is no more explanations for 1D input0, I thought when we set 1D {demissions:[n]} input0, the model would recognized it as 2D {demissions: [1, n]} using 1 for batch size, @Wenzhao-Xiang also thinks so. 
@huningxin please give your …
=> [test] Fixes #223 Add more CTS test cases for supported ops.

examples/image_classification/model/README.md
Base on the souce code below, the model files name should be resnet50v1 and resnet50v2 rather than 18.
```
const resnet_v1_onnx = {
modelName: 'ResNet50 v1(Onnx)',
modelFile: './model/resnet50v1.onnx',
...
};
const resnet_v2_onnx = {
modelName: 'ResNet50 v2(Onnx)',
modelFile: './model/resnet50v2.onnx',
...
};
```
@pinzhenx @Wenzhao-Xiang  please review.
=> [example] Fix typo issue for resnet model files name

README.md, package.json, webpack.config.js
Fix #477
- Upgrade Webpack from 3 to 4
- Replace `http-server` with `webpack-dev-server`
- Support hot reloading
- Support HTTPS
- Enable source map
=> upgrade webpack and dev server

examples/posenet/camera.js, examples/posenet/gui.js, examples/posenet/main.js, examples/posenet/src/PoseNet.js, examples/posenet/utils.js
**No ATROUS_DEPTHWISE_CONV2D:**
**ATROUS_DEPTHWISE_CONV2D:**
Performance: 
Only 20~30 ms speed up in WASM, and almost no speed up in WebGL.
=> [Example] Support atrous convolution in PoseNet example

.gitignore
The "ssd_mobilenet" path does not exist and the models filter rule has been covered by:
```
examples/**/*.tflite
examples/**/*.onnx
```
=> Remove ssd_mobilenet path in .gitignore

package.json
@ibelem PTAL, thanks
This PR is to fix CI fail on Linux platform. 
Since Chrome of CI environment is 70, the latest chromedirver(2.46.628388) supports between 71 and 75, so modify chromedirver as 2.45.0 in package.json to support Chrome 70.
=> [tool] Fix CI fail on Linux platform.

docs/api.md, docs/webml.idl, src/nn/Enums.js, src/nn/NeuralNetworkContext.js
reference: NNAPI https://android.googlesource.com/platform/frameworks/ml/+/refs/heads/master/nn/runtime/include/NeuralNetworks.h#3405
This op is available since API level 29.
=> [API][Polyfill] add MAXIMUM op

examples/static/css/style.css
Fix #774 
- Fix jitter issue in #/label/probability table of image classification with live camera view
- Fix jitter issue in inference time section
Test URL: https://ibelem.github.io/webml-website/examples/image_classification/?prefer=fast&b=WebML&m=mobilenet_v2_quant&t=tflite&s=camera&d=0
@huningxin @pinzhenx @Christywl PTAL
=> [example] fix jitter issue for inference time

examples/emotion_analysis/index.html, examples/emotion_analysis/main.js, examples/facial_landmark_detection/index.html, examples/facial_landmark_detection/main.js, examples/image_classification/index.html, examples/image_classification/main.js, examples/object_detection/index.html, examples/object_detection/main.js, examples/semantic_segmentation/index.html, examples/semantic_segmentation/main.js, examples/skeleton_detection/index.html, examples/skeleton_detection/main.js, examples/static/css/style.css, examples/static/js/ui.common.js, examples/super_resolution/main.js
Fix #809  @Wenzhao-Xiang @pinzhenx PTAL
@Christywl please check if any issues for switching cameras on mobile or tablet which support front-facing and rear cameras
Check points:
1. Switch display and layout on normal vs fullscreen
2. Swicth should work on Android (mobile phones)
3. Switch should be hidden for desktop browsers
4. The init camera should be correct for use cases, e.g. the Landmark should be front-facing camera by default rather than environment (rear) camera.
=> [Example] Supporting front-facing and rear cameras for mobile devices

examples/static/js/model.js
Update the Netron URL to https://intel.github.io/webml-polyfill/netron/ which added WebNN API Ops support status.
The Netron is MIT license based, so we can modify it and add to our gh-pages.
@BruceDai @Wenzhao-Xiang PTAL
=> [Example] Update Netron URL

.circleci/config.yml
Always get CI failure when [updating gh-pages](https://github.com/intel/webml-polyfill/commits/gh-pages),  so ignore gh-pages branch in circle ci config file.
@BruceDai @shenx3x @miaobin PTAL
=> [CI] Ignore gh-pages branch for Circle CI

.circleci/config.yml, examples/static/css/style.css, examples/static/js/ui.common.js
> do you still support api_info? flag? Latest build/examples don’t seem to support it. It’s a useful feature
When select "sustained" on Mac, it will show "MPS" text.
@Christywl PTAL
=> [Example] Add MPS badge when select sustained on Mac

benchmark/resources/utils.js
This bug was wrong operation by replacing `results.length` with `len` variable defined forward while the value of 'results.length' will change by 'results.shift()'. 
It has a little effect with our previous testing `mean` data before '+-' since we tested 200 iterations, but has some effect with `std` data. 
@ibelem PTAL, thanks
=> [benchmark] Fixed the bug of result summarize handling.

benchmark/resources/utils.js, benchmark/resources/utils_ic.js
Fix #964 
The original code in workload didn't consider the urls hosted from third party cloud service.
@BruceDai @cuiyanx PTAL
=> [workload] Fix #964 model and label 404 issue from storage service

examples/image_classification/utils.js, examples/semantic_segmentation/utils.js, examples/super_resolution/utils.js, examples/util/onnx/OnnxModelImporter.js, examples/util/openvino/OpenVINOModelImporter.js, examples/util/tflite/TFliteModelImporter.js
@ibelem  @BruceDai Please review, thanks! This tool can support models under WASM backend on Linux and Android, but can't work under WebML backend on Andriod.
=> [example] IterateLayers tool can work for quant model under WASM for these examples: image_classification, super_resolution and semantic_segmentation

docs/api.md, src/nn/Enums.js
@huningxin @fujunwei These two new ops were referring to [ARGMAX](https://developer.android.com/ndk/reference/group/neural-networks.html#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0af78048ff71a1e79bbc6034d30cad7cbc) and [ARGMIN](https://developer.android.com/ndk/reference/group/neural-networks.html#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0a89be86ff36e83254e9b3d0954e7e0729) of NN API, please take a review, thanks
=> [doc] Add ARGMAX op.

src/nn/wasm/src/bind/src/binding.cpp
=> [WASM] Fixed a build error caused by Emscripten version

.circleci/config.yml
@ibelem The last PR #1069 couldn't be verified locally,  when it's merged, I found #1068 still reproduced online, so I submitted this one to both upgrade docker image for CircleCI.  PTAL, thanks.
=> [ci] Upgraded CircleCI using 13.1.0-browsers docker image.

test/cts/tool/CTSConverter/slice.json, test/cts/tool/CTSConverter/src/nn/specs/V1_3/avg_pool_quant8_signed.mod.py, test/cts/tool/CTSConverter/src/nn/specs/V1_3/conv2d_quant8_signed.mod.py, test/cts/tool/CTSConverter/src/nn/specs/V1_3/depthwise_conv2d_quant8_signed.mod.py, test/cts/tool/CTSConverter/src/nn/specs/V1_3/softmax_quant8_signed.mod.py, test/cts/tool/CTSConverter/src/test_generator.py
Update CTSConverter to support new ops with int8 datatype：
1. avg_pool
2. conv2d
3. depthwise_conv2d
4. softmax
=> [tool] Update CTSConverter to support new ops

test/cts/test/V1_0_plus/depthwise_conv2d_float_large_2_weights_as_inputs_relu.js, test/cts/test/V1_0_plus/depthwise_conv2d_float_large_2_weights_as_inputs_relu1.js, test/cts/test/V1_0_plus/depthwise_conv2d_float_large_2_weights_as_inputs_relu6.js
Update these three CTS tests using Relu activations align with updated [V1_0/depthwise_conv2d_float_large_2_weights_as_inputs.js](https://github.com/intel/webml-polyfill/blob/master/test/cts/test/V1_0/depthwise_conv2d_float_large_2_weights_as_inputs.js).
@mingmingtasd @ibelem PTAL, thanks.
=> [test] Updated three depthwise_conv2d tests using Relu activations align with updated V1_0/depthwise_conv2d_float_large_2_weights_as_inputs.js

test/cts/test/V1_3/avg_pool_quant8_signed.js
Add 5 CTS test cases for "Avg_pool" op with `TENSOR_QUANT8_ASYMM_SIGNED` input. 
op | cts | plus | supplement
-- | -- | -- | --
Avg_pool | 5 | 0 | 0
fixes #1212
=> [test] Add CTS test cases for avg_pool op

examples/emotion_analysis/EmotionAnalysisExample.js, examples/face_recognition/FaceRecognitionExample.js, examples/facial_landmark_detection/FacialLandmarkDetectionExample.js, examples/util/BaseExample.js
This PR is to fix memory issue by Wasm/WebGL backend when model changed of examples using multi models. The last @akineeic PR #1264 works with examples using single model.
@huningxin @ibelem @akineeic PTAL, thanks.
=> [example] Fixed memory issue by Wasm/WebGL backend when model changed of examples using multi models.

test/tools/CI/baseline/baseline.config.json, test/tools/CI/baseline/unitTestsBaseline.csv
One MAXIMUM test case failed with TF.js Wasm backend(#1253), so update CI baseline data for this.
=> [tools] Update CI baseline data for new Wasm backend

src/nn/tfjs/TfjsModel.js
=> [WASM] Temporary fix of tfjs-bankend-wasm 2.0.1 init issue

test/utils.js
For PR #1203,  use prefer=sustained&webgpu=true parameters to enable test by WebGPU backend on Windows and macOS platforms, since 'Unsafe WebGPU' flag only works on Windows and macOS platforms. 
@huningxin @ibelem @NALLEIN  PTAL, thanks
=> [test] Enabled test by WebGPU backend using prefer=sustained&webgpu=true parameters.

package.json, src/nn/Compilation.js, src/nn/Model.js, src/nn/NeuralNetworkContext.js, src/nn/tfjs/TfjsModel.js
@huningxin @ibelem PTAL, thanks. 
I use **require** to instead of **import** for '@tensorflow/tfjs-backend-webgpu' model, now if browser didn't support WebGPU, there's an error 'WebGPU is not available'.
```js
static _supportWebGPU() {
if (navigator.gpu === undefined) {
return false;
} else {
let tfjsBackendWebgpu = require("@tensorflow/tfjs-backend-webgpu");
tf.setBackend('webgpu');
tf.ready();
return tf.getBackend() === "webgpu";
}
}
```
=> [polyfill] Supported WebGPU backend.

examples/static/img/favicon/site.webmanifest
It will show HTTP 404 for android-chrome-192x192.png in Chrome 85 when visiting https://intel.github.io/webml-polyfill/examples/, this PR just fix this error.
@BruceDai PTAL. It's been fixed in gh-pages branch.
=> [Example] Fix favicon 404 issue in new Chrome browser

examples/semantic_segmentation/index.html, examples/util/WebNNRunner.js, examples/util/modelZoo.js, examples/util/openvino/OpenVINOModelImporter.js, examples/util/openvino/OpenVINOModelUtils.js, examples/util/openvino/openvino.js, src/nn/Model.js, src/nn/tfjs/TfjsModel.js
Now we have supported the f32 openvino models with new version IR v10. Deeplabv3 int8 models with differenrt input sizes (224, 257, 321, 513) are also supported. Remind that we should update the openvino model files to IR v10 correspondingly. PTAL, thanks! @BruceDai @belem @lisa0314 @miaobin
=> Support f32 and deeplabv3 int8 models with new openvino model version IR v10
